=== Generating Salesforce DTOs with the `salesforce-maven-plugin`

[NOTE]
====
The `camel-salesforce-maven-plugin` is only covered by community support.
====

To generate Salesforce DTOs for your project, use the `salesforce-maven-plugin`. The example code snippet below creates a single DTO for the `Account` object.

[source,xml,subs="attributes+"]
----
<plugin>
    <groupId>org.apache.camel.maven</groupId>
    <artifactId>camel-salesforce-maven-plugin</artifactId>
    <version>{camel-version}</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <clientId>${env.SALESFORCE_CLIENTID}</clientId>
                <clientSecret>${env.SALESFORCE_CLIENTSECRET}</clientSecret>
                <userName>${env.SALESFORCE_USERNAME}</userName>
                <password>${env.SALESFORCE_PASSWORD}</password>
                <loginUrl>https://login.salesforce.com</loginUrl>
                <packageName>org.apache.camel.quarkus.component.salesforce.generated</packageName>
                <outputDirectory>src/main/java</outputDirectory>
                <includes>
                    <include>Account</include>
                </includes>
            </configuration>
        </execution>
    </executions>
</plugin>
----

=== Register additional Salesforce classes for reflection in native mode

For native mode, it is necessary to register some additional classes for reflection.

1. Classes in package `org.apache.camel.component.salesforce.api.dto`
2. DTO classes generated by the `camel-salesforce-maven-plugin`

To do this, add the following configuration property to `application.properties`. Replace `org.my.custom.dto.package` with your custom DTO package (if applicable, othwerwise it can be be removed).

[source,properties]
----
quarkus.camel.native.reflection.include-patterns=org.apache.camel.component.salesforce.api.dto.*,org.my.custom.dto.package.*
----
