= Camel Quarkus Product

* This Maven Module should never leak to the ASF repo

== `camel-quarkus-product-source.json`

* The format of `camel-quarkus-product-source.json` is under our control and independent from `camel-quarkus-product.json` which is controlled by Quarkus.
* We want to be able to have additional info in `camel-quarkus-product-source.json`, that we can use e.g. when doing partial productization or generating parts of our documentation.

=== Schema

* `extensions` - a map from extension artifactIds to extension metadata.
  Only productized extensions are listed here.
  This list actually controls which modules get unlinked from the source tree by `cq-prod-maven-plugin:prod-excludes` mojo.
* `extensions.<artifactId>.allowedMixedTests` - if defined and set to a non-empty array of artifactIds,
  accept the mixed tests covering the given extension.
* `extensions.<artifactId>.[jvm|native]` - The support status: possible values: `community`, `techPreview`, `supported`
* `extensions.<artifactId>.comment` - A free form comment
* `additionalProductizedArtifacts` - an array of artifactIds to include in the product build.
  Unlike `extensions.<artifactId>`, these are not extensions.

=== Updating the source tree after changing `camel-quarkus-product-source.json`

Run the following from the root directory of the source tree:

[source,shell]
----
$ mvn org.l2x6.cq:cq-prod-maven-plugin:prod-excludes -N
$ mvn clean install -Dquickly
$ mvn org.l2x6.cq:cq-prod-maven-plugin:transitive-deps -N
----

and commit the changes.

If `product/src/main/generated/required-productized-camel-artifacts.txt` was changed
it needs to get copied to the corresponding Camel branch - the `product/README.adoc` in Camel.

Note that the consistency of the source tree with `camel-quarkus-product-source.json` is checked by
the `cq-prod-maven-plugin:prod-excludes-check` mojo bound to `validate` phase of the build.

The `transitive-deps` mojo needs to be run after `install` because it relies on Camel Quarkus artifacts and all their transitive dependencies being available in the local Maven repo at least.

=== The modified source tree

==== Build and test the productized part

The default profile-less build `mvn clean install` will include

* All productized extensions
* A mixed BOM
* Tests that cover productized extensions and have no non-productized dependencies.
  These tests can be run via `cd product/integration-tests-product && mvn verify -Pnative`.

Note that the default profile-less build `mvn clean install` will *not* include all tests
necessary to cover the productized extensions.
This is the case because some productized extensions are covered by tests requiring non-productized artifacts.
Those tests that are really essential for covering the productized extensions are called "allowed mixed tests".
They are explicitly marked via `extensions.<artifactId>.allowedMixedTests` in `camel-quarkus-product-source.json`.
To run them you need to

[source,shell]
----
$ cd product/integration-tests-mixed-allowed && mvn clean verify -Pmixed,native
----

==== Run the rest of the mixed tests

[source,shell]
----
$ cd product/integration-tests-mixed-jvm && mvn clean test -Pmixed
$ cd product/integration-tests-mixed-native && mvn clean verify -Pmixed,native
----

== `camel-quarkus-product.json`

* `target/camel-quarkus-product.json` is generated by `src/main/groovy/generate-camel-quarkus-product-json.groovy` from `src/main/resources/camel-quarkus-product-source.json`
* `target/camel-quarkus-product.json` is a list of Camel Quarkus extensions supported (or being tech-preview) in Camel Quarkus product
* `target/camel-quarkus-product.json` is used by Quarkus tooling in https://github.com/quarkusio/quarkus-platform[Quarkus Platform]
