= Camel Quarkus Product

* This Maven Module should never leak to the ASF repo

== `camel-quarkus-product-source.json`

* The format of `camel-quarkus-product-source.json` is under our control and independent from `camel-quarkus-product.json` which is controlled by Quarkus.
* We want to be able to have additional info in `camel-quarkus-product-source.json`, that we can use e.g. when doing partial productization or generating parts of our documentation.

=== Schema

* `extensions.<artifactId>.allowedMixedTests` - if defined and set to a non-empty array of artifactIds,
  accept the mixed tests covering the given extension.

== `camel-quarkus-product.json`

* `target/camel-quarkus-product.json` is generated by `src/main/groovy/generate-camel-quarkus-product-json.groovy` from `src/main/resources/camel-quarkus-product-source.json`
* `target/camel-quarkus-product.json` is a list of Camel Quarkus extensions supported (or being tech-preview) in Camel Quarkus product
* `target/camel-quarkus-product.json` is used by Quarkus tooling in https://github.com/quarkusio/quarkus-platform[Quarkus Platform]

== `.mvn/excludes.txt`

* Generated from `camel-quarkus-product-source.json` via
+
[source,shell]
----
$ mvn org.l2x6.cq:cq-prod-maven-plugin:prod-excludes -N
----
+
* The consistency of `.mvn/excludes.txt` with `camel-quarkus-product-source.json` is checked by
  `cq-prod-maven-plugin:prod-excludes-check` bound to `validate` phase of the build.
