== Testing

=== Running all tests at once

By default the tests are run against `io.quarkus:quarkus-bom` and `org.apache.camel.quarkus:camel-quarkus-bom` versions defined/present in the source tree:

E.g. the following would run all product relevant tests in JVM mode against the current SNAPSHOT of `org.apache.camel.quarkus:camel-quarkus-bom` present in local Maven repository:

[source,shell]
----
$ cd product
$ mvn clean test -Dformatter.skip -Dimpsort.skip -DnoVirtualDependencies -fae
----

To run also tests of non-supported extensions, you'd have to add `-Pmixed`.

To run the tests (the ones which support it) in native mode, replace `test` with `verify -Pnative`.

=== Running the tests against Quarkus Platform BOMs

The test modules accept certain parameters which can be used to run the tests against some alternative BOMs, such as RHBQ Platform BOMs.

E.g. to run the tests against against RHBQ BOMs 2.7.5.SP1-redhat-00001 (that is based on CEQ 2.7.1.redhat-00016), you need to do the following:

[source,shell]
----
$ cd product
$ PLATFORM_VERSION=2.7.5.SP1-redhat-00001
$ CEQ_VERSION=2.7.1.redhat-00016
$ git remote -v
gerrit  ssh://<your-username>@code.engineering.redhat.com/jboss-fuse/camel-quarkus (fetch)
gerrit  ssh://<your-username>@code.engineering.redhat.com/jboss-fuse/camel-quarkus (push)
...
$ git fetch gerrit $CEQ_VERSION
$ git checkout FETCH_HEAD
$ git tag $CEQ_VERSION
$ mvn clean test -Dformatter.skip -Dimpsort.skip -DnoVirtualDependencies -fae \
  -Dquarkus.platform.group-id=com.redhat.quarkus.platform \
  -Dquarkus.platform.artifact-id=quarkus-bom \
  -Dquarkus.platform.version=$PLATFORM_VERSION \
  -Dcamel-quarkus.platform.group-id=com.redhat.quarkus.platform \
  -Dcamel-quarkus.platform.artifact-id=quarkus-camel-bom \
  -Dcamel-quarkus.platform.version=$PLATFORM_VERSION \
  -Dcamel-quarkus.version=$CEQ_VERSION
----

To run also tests of non-supported extensions, you'd have to add `-Pmixed`.

To run the tests (the ones which support it) in native mode, replace `test` with `verify -Pnative`.

=== Groups of tests
We have multiple categories of tests distinguished by level of support (Supported/Community) and by given runtime (JVM/Native). Those categories can be found under `product` folder.

==== Supported extensions
We have these folders:

- integration-tests-mixed-allowed (For both JVM and Native)
- integration-tests-product (For both JVM and Native)

==== Community extensions
We have these folders:

- integration-tests-mixed-jvm (Only for JVM)
- integration-tests-mixed-native (For both JVM and Native)

Each category is granularized even more so every category can have multiple groups which is designed for being able to run those groups in parallel.

==== Run group of tests
To run specific group, just step into the path (eg. product/integration-tests-product/group-01) and invoke:

[source,shell]
----
 mvn -U -B -e -V -ntp verify -Dformatter.skip -Dimpsort.skip -Denforcer.skip -Dcamel-quarkus.update-extension-doc-page.skip -DnoVirtualDependencies -Dcamel-quarkus.version=$VERSION_CAMEL_QUARKUS -Dquarkus.platform.group-id=io.quarkus -Dquarkus.platform.artifact-id=quarkus-bom -Dquarkus.platform.version=$VERSION_QUARKUS -Dcamel-quarkus.platform.group-id=org.apache.camel.quarkus -Dcamel-quarkus.platform.artifact-id=camel-quarkus-bom -Dcamel-quarkus.platform.version=$VERSION_CAMEL_QUARKUS -Pmixed
----

=== Single test module
The base command which should be run from root folder of this project looks like follows:

[source,shell]
----
 mvn -U -B -e -V -ntp verify -Dformatter.skip -Dimpsort.skip -Denforcer.skip -Dcamel-quarkus.update-extension-doc-page.skip -DnoVirtualDependencies -Dcamel-quarkus.version=$VERSION_CAMEL_QUARKUS -Dquarkus.platform.group-id=io.quarkus -Dquarkus.platform.artifact-id=quarkus-bom -Dquarkus.platform.version=$VERSION_QUARKUS -Dcamel-quarkus.platform.group-id=org.apache.camel.quarkus -Dcamel-quarkus.platform.artifact-id=camel-quarkus-bom -Dcamel-quarkus.platform.version=$VERSION_CAMEL_QUARKUS -Pmixed -pl :camel-quarkus-product,:<artifact-id-of-test-module>
----

Note the command above is for JVM tests, for tests run in Native please add `-Pnative,docker '-Dtest=!*'` which will enable native tests and disable JVM tests.

We can also specify single test via `-Dtest=<test_name>` for JVM or `-Dit.test=<test_name>` in case of Native.

